version: '3.5'

services:

  web:
    container_name: "web"
    build: ./web

    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 1111:1111
    networks:
      - custom
    depends_on:
      - db

  db:
    container_name: "db"
    image: postgres:13-alpine
    volumes:
      - ./db_dev/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    networks:
      - custom

volumes:
  db_dev:
    name: db_dev

networks:
  custom:
    driver: bridge